import type { Theme } from './types'

// ---------------------------------------------------------------------------
// Built-in themes. These ship with the app and can't be deleted.
//
// To make an admin-created theme permanent: open the Admin panel, design it,
// hit "Export .ts", and paste the generated object into this array.
// ---------------------------------------------------------------------------

export const BUILTIN_THEMES: Theme[] = [
  {
    id: 'overworld',
    name: 'Overworld',
    icon: '🌳',
    kind: 'overworld',
    colors: {
      bgTop: '#79c3ff',
      bgBottom: '#c9f0a7',
      fog: 'rgba(255,255,255,0.10)',
      panel: '#3b3b44',
      panel2: '#2b2b31',
      borderLight: '#6f6f7a',
      borderDark: '#141417',
      text: '#f4f4f2',
      textDim: '#a9c98c',
      accent: '#6aa84f',
      accent2: '#b6e36a',
      slot: '#8b8b8b',
      particle: '#ffffff',
    },
    blocks: ['grass', 'dirt', 'stone', 'diamond_ore', 'crafting_table'],
  },
  {
    id: 'nether',
    name: 'The Nether',
    icon: '🔥',
    kind: 'nether',
    colors: {
      bgTop: '#2a0808',
      bgBottom: '#6b1608',
      fog: 'rgba(255,90,20,0.10)',
      panel: '#3a1414',
      panel2: '#260c0c',
      borderLight: '#7a2a1e',
      borderDark: '#120404',
      text: '#ffd9c4',
      textDim: '#e0794f',
      accent: '#ff5a1f',
      accent2: '#ffd54a',
      slot: '#5a2420',
      particle: '#ff7a2a',
    },
    blocks: ['netherrack', 'obsidian', 'gold_ore', 'glowstone', 'tnt'],
  },
  {
    id: 'end',
    name: 'The End',
    icon: '🐉',
    kind: 'end',
    colors: {
      bgTop: '#0a0813',
      bgBottom: '#241a3a',
      fog: 'rgba(160,120,255,0.08)',
      panel: '#241f33',
      panel2: '#171426',
      borderLight: '#4a3f6b',
      borderDark: '#0b0916',
      text: '#efeaff',
      textDim: '#b7a6e6',
      accent: '#b98cff',
      accent2: '#8ff0e0',
      slot: '#3a3355',
      particle: '#cbb6ff',
    },
    blocks: ['end_stone', 'purpur', 'obsidian', 'sculk'],
  },
  {
    id: 'deepdark',
    name: 'Deep Dark',
    icon: '🌀',
    kind: 'cave',
    colors: {
      bgTop: '#04070a',
      bgBottom: '#0a1418',
      fog: 'rgba(20,160,150,0.07)',
      panel: '#111a1d',
      panel2: '#0a1113',
      borderLight: '#274044',
      borderDark: '#030607',
      text: '#dff7f2',
      textDim: '#4fb3a6',
      accent: '#1fd3c0',
      accent2: '#0f8fff',
      slot: '#1a2a2c',
      particle: '#28e0cc',
    },
    blocks: ['sculk', 'obsidian', 'stone', 'diamond_ore', 'emerald_ore'],
  },
  {
    id: 'aether',
    name: 'Aether',
    icon: '☁️',
    kind: 'sky',
    colors: {
      bgTop: '#eaf6ff',
      bgBottom: '#bfe0ff',
      fog: 'rgba(255,255,255,0.28)',
      panel: '#e7ecf5',
      panel2: '#cdd8ea',
      borderLight: '#ffffff',
      borderDark: '#8fa6c4',
      text: '#243b53',
      textDim: '#5f7a99',
      accent: '#3a8fff',
      accent2: '#f6c945',
      slot: '#c3d2e6',
      particle: '#ffffff',
    },
    blocks: ['glowstone', 'lapis_ore', 'diamond_ore', 'grass'],
  },
]

export const DEFAULT_THEME_ID = 'overworld'
